### PR TITLE
auto/fix walkway dead lock

### PR DESCRIPTION
**Pull request by taikitanaka3**
## Description

- bugfix

change walkway stop decision form relative distance to arc lane distance in order to avoid dead lock

Change
condition of walkway expired is "stop near walkway" to "stop near walkway" or "stop after walkway"

Screenshot from 2021-11-29 16-28-58

## Review Procedure

use rqt_publisher to manually override ego vehicle and see if walkway that ego vehicle passed is expired after stop
https://user-images.githubusercontent.com/65527974/143822890-b4ea74a5-cd57-41ce-8b34-6cfa798daeb5.mp4

see normal behavior is the same as before(stop line and walkway).
https://user-images.githubusercontent.com/65527974/143827037-5349a87b-1008-44a8-b651-ca71b27d131f.mp4

## Remarks

This kind of behavior change is going to added after December

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [pull request guidelines][pull-request-guidelines]
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yukkysaito** [comment]
@taikitanaka3 これってなぜデッドロック起きてたんですか？

**Comment by taikitanaka3** [comment]
@yukkysaito 
曲率の高い経路で制御の追従誤差が大きいときや、手動運転で停止せず（各モジュールで定めている停止判定を満たさず）に通過したときなど起きてました。

**Comment by yukkysaito** [comment]
@taikitanaka3 了解です。以前ちょっと相談したかもですが、できればstop line モジュールをライブラリ化して、walk wayとかでも使い回せるようにしたいですね :+1: 今回のsign arcとかもstop line側では一通り対策しています

**Comment by taikitanaka3** [comment]
@yukkysaito 
https://github.com/tier4/AutowareArchitectureProposal.iv/blob/a8903e268b455ca424e90cca00cf180eb2f0f1ac/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/src/scene_module/stop_line/scene.cpp#L294
stop line でもarc lane座標系を使用しているのですが、この部分が絶対値の場合デッドロックは起こってしまうので,
最小の変更だとstd::absを外す必要があります。ただ、autoware utilにも関数があるのでそちらを利用しました。

**Pull request closed without merging**
