### PR TITLE
autoware_web_controller port to .auto

### PR DESCRIPTION
**Pull request by YoheiMishina**
## Description
Sport to autoware_auto_msgs
 autoware_vehicle_msgs/Engage to autoware_auto_vehicle_msgs/Engage
 autoware_system_msgs/AutowareState to autoware_auto_system_msgs/AutowareState

ignore msgs, because, these message not exist in autoware_auto_msgs.
 autoware_planning_msgs/msg/Approval
 autoware_vehicle_msgs/ControlMode
 autoware_planning_msgs/VelocityLimit

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [pull request guidelines][pull-request-guidelines]
- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@YoheiMishina Please update the PR title to be more specific.

**Comment by YoheiMishina** [comment]
> @YoheiMishina Please update the PR title to be more specific.

dane

**Comment by tkimura4** [comment]
Could you update this line?

https://github.com/tier4/AutowareArchitectureProposal.iv/blob/6a596a30bb5a1c23b9c20fdebddf3caa530acb7d/common/util/web_controller/autoware_web_controller/www/autoware_web_controller/index.html#L37

**Comment by YoheiMishina** [comment]
> Could you update this line?
> 
> https://github.com/tier4/AutowareArchitectureProposal.iv/blob/6a596a30bb5a1c23b9c20fdebddf3caa530acb7d/common/util/web_controller/autoware_web_controller/www/autoware_web_controller/index.html#L37



> Could you update this line?
> 
> https://github.com/tier4/AutowareArchitectureProposal.iv/blob/6a596a30bb5a1c23b9c20fdebddf3caa530acb7d/common/util/web_controller/autoware_web_controller/www/autoware_web_controller/index.html#L37

I update url : f2721d1cf7a4360900b8558db8a9ad4285ad5369

**Review by tkimura4 — APPROVED** [review]

**Pull request merged**
