### PR TITLE
Auto/autoware utils colcon ignore

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

remove COLCON_IGNORE in autoware_utils

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [pull request guidelines][pull-request-guidelines]
- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by takayuki5168** [comment]
@kenji-miyake @TakaHoribe 
Auto-merge was set in the autoware_utils porting PR, and the PR was merged automatically though I'm still working on it.
I opened a new one, just removing COLCON_IGNORE, and that's all for autoware_utils porting.

https://github.com/tier4/AutowareArchitectureProposal.iv/pull/489

**Review by taikitanaka3 — APPROVED** [review]

**Comment by taikitanaka3** [comment]
@kenji-miyake @takayuki5168 
require dependency?
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
autoware_utils: Cannot locate rosdep definition for [autoware_lint_common]
```

**Comment by takayuki5168** [comment]
@taikitanaka3 I've mentioned to Miyake-san on Slack.

**Comment by kenji-miyake** [comment]
You have to remove `autoware_lint_common/COLCON_IGNORE`.

**Pull request merged**
