### PR TITLE
[external_cmd_converter] apply autoware auto msgs

### PR DESCRIPTION
**Pull request by taikitanaka3**
## Description

below change
- twist -> odometry
- control command stamped -> AckermannControlCommand
- shift stamped -> VehicleStateCommand

unchanged
- autoware_external_api_msgs
- gate_mode
- topic name for shift remain unchanged

changed
- ackermann_control_command
- gear_command
- odometry

pkg depends
https://github.com/tier4/AutowareArchitectureProposal.iv/pull/519

## Review Procedure

colcon build pass
launch s

```
/control/current_gate_mode
/diagnostics
/external/selected/control_cmd
/external/selected/external_control_cmd
/external/selected/heartbeat
/external/selected/shift_cmd
/localization/kinematic_state
/parameter_events
/rosout
```
## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [pull request guidelines][pull-request-guidelines]
- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by takayuki5168** [comment]
raw vehicle cmd converter must be ported first.
image

**Comment by tkimura4** [comment]
@taikitanaka3 
could you rebase this and reflect this PR https://github.com/tier4/AutowareArchitectureProposal.iv/pull/519 ?

**Comment by taikitanaka3** [comment]
@tkimura4 @takayuki5168 
can you take a look at later?

**Review by tkimura4 — APPROVED** [review]
LGTM

**Pull request merged**
