### PR TITLE
rename topic name twist -> odometry

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

rename twist to odometry

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [pull request guidelines][pull-request-guidelines]
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by takayuki5168** [comment]
This relates to this launcher update
https://github.com/tier4/AutowareArchitectureProposal_launcher/pull/109

I'll look into more when trying planning_simulator lator, so it's merge ready for this PR now

**Comment by taikitanaka3** [comment]
@takayuki5168 
is there any other packages that still rcieves `/localization/twist` ?

**Review by taikitanaka3 — APPROVED** [review]

**Comment by takayuki5168** [comment]
@taikitanaka3 In P/C packages, this is all.

**Comment by taikitanaka3** [comment]
@takayuki5168 
for control packages can you modify obstacle collision checker and lane departure checker as well

**Comment by takayuki5168** [comment]
Ah sorry, this is only planning packages. I'll change control packages as well.

**Comment by takayuki5168** [comment]
It seems in control, there are no packages that uses /localization/twist?
Anyway most of the control packages are under porting, so I will look into this translation in control packages later.
Is it ok? If so, I think it's merge ready

**Comment by taikitanaka3** [comment]
@takayuki5168 
All right

**Pull request merged**
