### PR TITLE
port surround obstacle checker

### PR DESCRIPTION
**Pull request by Sugatyon**
## Description
.auto ポーティング

autoware_planning_msgs::msg::Trajectory
→
autoware_auto_planning_msgs::msg::TrajectoryPoint

autoware_perception_msgs::msg::DynamicObjectArray
→
autoware_auto_perception_msgs::msg::PredictedObjects

## Remarks

以下の変更がmergeされる前提でporting
https://github.com/tier4/autoware_auto_msgs/pull/7

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [pull request guidelines][pull-request-guidelines]
- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by Sugatyon** [comment]
@TakaHoribe 
merge readyですっ！

**Comment by TakaHoribe** [comment]
@Sugatyon ドラフトの解除を・・・！

**Comment by Sugatyon** [comment]
@TakaHoribe 
😱😱
解除しました！

**Comment by TakaHoribe** [comment]
@Sugatyon 
 - twist->odomの変換がされてないです？
 - autoware_perception_msgsは依存消えました？packages.xmlにはまだ残ってるので、これは消してok？
 - autoware_planning_msgsの依存はstopReasonだけでしょうか？（エクセルに記載お願いします）

**Comment by Sugatyon** [comment]
@TakaHoribe 
確認漏れててすみません。

> twist->odomの変換がされてないです？
> autoware_perception_msgsは依存消えました？packages.xmlにはまだ残ってるので、これは消してok？
対応しました！
> autoware_planning_msgsの依存はstopReasonだけでしょうか？（エクセルに記載お願いします）
StopReason、StopReasonArray、StopFactorがautoware_planning_msgsに依存しているので、エクセルに記載しました。

**Review by TakaHoribe — APPROVED** [review]

**Pull request merged**
