### PR TITLE
Fix concatenate data

### PR DESCRIPTION
**Pull request by wep21**
* Remove std msgs from concatenate data
* Adaptive timer(https://github.com/tier4/AutowareArchitectureProposal.iv/issues/119)

### CODE REVIEW

**Comment by tkimura4** [comment]
As far as I can see the code, it looks fine.
How can I verify the operation?（Is it okay to merge without operation verification?）

**Comment by mitsudome-r** [comment]
I've changed the target branch to ros2.

**Comment by wep21** [comment]
@tkimura4 Could you check with rosbag as below?
* `ros2 run pointcloud_preprocessor concatenate_data_node --ros-args -p output_frame:=base_link -p input_topics:=[/sensing/lidar/left/outlier_filtered/pointcloud, /sensing/lidar/right/outlier_filtered/pointcloud, /sensing/lidar/rear/outlier_filtered/pointcloud]`
* `ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 map base_link`
* `ros2 param set /point_cloud_concatenator_component use_sim_time true`
* `rviz2 -d concatenate_test.rviz`
* `ros2 param set /rviz2 use_sim_time true`
* `ros2 bag play rosbag2_2021_03_03-11_55_33`
I will send you a bag file later.

**Comment by kenji-miyake** [comment]
@tkimura4 @wep21 FYI: We've tested this with a real-vehicle and it worked.

**Comment by tkimura4** [comment]
image

**Review by tkimura4 — APPROVED** [review]
LGTM

**Pull request merged**
