### PR TITLE
Fix typo in planning module

### PR DESCRIPTION
**Pull request by kmiya**
Fix typo in the planning module.
Please merge this with the following pull request simultaneously.
https://github.com/tier4/autoware_launcher.iv.universe/pull/92

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Everything looks fine.

**Comment by kenji-miyake** [comment]
I've fixed some remaining errors in this commit.
https://github.com/tier4/AutowareArchitectureProposal.iv/pull/432/commits/8c83686901efd44621e740a37555edebe13b0687

@kmiya @k0suke-murakami Could you check this and other parameters, please?

**Comment by k0suke-murakami** [comment]
Could you modify the codes so that CI would pass?

**Comment by kmiya** [comment]
Ah, it must be a cpplint and uncrustify thing. Will fix them.

**Comment by kmiya** [comment]
Tests have passed :partying_face:

**Review by k0suke-murakami — APPROVED** [review]
LGTM

**Pull request merged**
