### PR TITLE
port planning rviz plugins

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

autoware planning rviz pluginの.auto porting

**TODO**
autoware_planning_msgs::VelocityLimitのみiv_msgsに依存

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [pull request guidelines][pull-request-guidelines]
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by taikitanaka3** [comment]
```
Starting >>> autoware_datetime_rviz_plugin
Starting >>> autoware_localization_rviz_plugin
Starting >>> autoware_perception_rviz_plugin
Starting >>> autoware_planning_rviz_plugin
Starting >>> autoware_state_rviz_plugin
Starting >>> autoware_vehicle_rviz_plugin
Starting >>> npc_simulator_rviz_plugin
Starting >>> grid_map_rviz_plugin
Finished <<< autoware_localization_rviz_plugin [0.51s]                                                                                     
Finished <<< autoware_state_rviz_plugin [0.49s]
Finished <<< autoware_datetime_rviz_plugin [0.54s]
Finished <<< autoware_perception_rviz_plugin [0.55s]
Finished <<< npc_simulator_rviz_plugin [0.52s]
Finished <<< autoware_vehicle_rviz_plugin [0.57s]                                                                                 
Finished <<< grid_map_rviz_plugin [0.56s]
Finished <<< autoware_planning_rviz_plugin [0.61s]

Summary: 8 packages finished [1.33s]
```
@takayuki5168 
TODOは別PRにしますか？それともこのPRで変更します？

**Comment by takayuki5168** [comment]
@taikitanaka3 https://star4.slack.com/archives/C02JH3FME8N/p1636019733411400?thread_ts=1636018741.408000&cid=C02JH3FME8N
この通りTODOのままマージしちゃいます！

**Comment by takayuki5168** [comment]
merge ready

**Review by taikitanaka3 — APPROVED** [review]
@takayuki5168 
LGTM

**Comment by taikitanaka3** [comment]
@kenji-miyake
これのPRはbuild pass しているのですがcolcon Ignore追加のPRを取り込む必要ありそうでしょうか？

**Comment by kenji-miyake** [comment]
@taikitanaka3 Yes, because after merging this, it will be ignored. So you have to remove `COLCON_IGNORE` here.

**Comment by takayuki5168** [comment]
@taikitanaka3 Check again please, and if no probelm, could you merge?

**Review by taikitanaka3 — APPROVED** [review]
```
100% tests passed, 0 tests failed out of 4

Label Time Summary:
copyright     =   1.25 sec*proc (1 test)
cppcheck      =   0.40 sec*proc (1 test)
lint_cmake    =   0.32 sec*proc (1 test)
linter        =   2.29 sec*proc (4 tests)
xmllint       =   0.32 sec*proc (1 test)

Total Test time (real) =   2.29 sec
Finished <<< autoware_planning_rviz_plugin [2.45s]

Summary: 1 package finished [3.05s]
```
LGTM

**Pull request merged**
