### PR TITLE
port scenario_selector

### PR DESCRIPTION
**Pull request by takayuki5168**
## PR Type

.autoポーティング

## Description

scenario_selector

**TODO**
Scenarioはiv_msgsを使用

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [pull request guidelines][pull-request-guidelines]
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by takayuki5168** [comment]
に

**Comment by takayuki5168** [comment]
@taikitanaka3 Could you review? I reopend the PR to build again just in case.

**Comment by taikitanaka3** [comment]
@takayuki5168 
I think you need to remove colcon ignore in this commit

**Comment by takayuki5168** [comment]
@taikitanaka3 Ahh sorry, I was confused. :bow:

**Comment by taikitanaka3** [comment]
@takayuki5168 
you removed obstacle avoidance 's ignore 
you need to remove scenario selector 's

**Comment by takayuki5168** [comment]
@taikitanaka3 OMG :innocent: My bad

**Comment by taikitanaka3** [comment]
@takayuki5168 
Dont mind

**Comment by takayuki5168** [comment]
TODO: use odometry instead of twist here

**Comment by takayuki5168** [comment]
finished porting

**Review by taikitanaka3 — APPROVED** [review]
@TakaHoribe 
merge ready 
- [x] remove ignore
- [x] package depends
- [x] build pass

**Comment by taikitanaka3** [comment]
@takayuki5168 
maybe changed ?
https://tier4.atlassian.net/wiki/spaces/ATWROSS/pages/2162590456/2021-11-05+.IV+.Auto+merge+sync

**Comment by TakaHoribe** [comment]
IFはとりあえずこれで良いです。方針が変わったらまた追って修正しましょう。

**Review by TakaHoribe — APPROVED** [review]

**Pull request merged**
