### PR TITLE
[update to v0.8.0] vehicle cmd gate

### PR DESCRIPTION
**Pull request by TakaHoribe**
## TODO
 - [ ] check usage of service

### CODE REVIEW

**Comment by k0suke-murakami** [comment]
- [x]  Build passed
 Packge: vehicle_cmd_gate

- [x] ros2 run success.
 Node : vehicle_cmd_gate
 
- [x] Test  passed

**Comment by k0suke-murakami** [comment]
> ## TODO
> * [ ]  check usage of service

Is this PR ready to be merged? Or you need to do something in service? @TakaHoribe

**Comment by TakaHoribe** [comment]
@k0suke-murakami Ready for merge!

**Comment by k0suke-murakami** [comment]
- [x]  Build passed
 Packge: vehicle_cmd_gate

- [x] ros2 run success.
 Node : vehicle_cmd_gate
 
- [x] Test  passed

**Pull request merged**
