### PR TITLE
port obstacle collision checker

### PR DESCRIPTION
**Pull request by takayuki5168**
## PR Type

.autoポーティング

## Description

obstacle collision checker

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [pull request guidelines][pull-request-guidelines]
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@takayuki5168 To make the diff clean, please change the target branch to `auto/autoware-utils`.

**Comment by takayuki5168** [comment]
@kenji-miyake Sorry I forgot to do that :pray:

**Comment by takayuki5168** [comment]
@taikitanaka3 Could you

**Review by taikitanaka3 — APPROVED** [review]
@takayuki5168 
mainly repalce to autoware_auto_planning_msgs 
```
Starting >>> obstacle_collision_checker
Finished <<< obstacle_collision_checker [20.8s]                       

Summary: 1 package finished [21.4s]
```
LGTM

**Comment by taikitanaka3** [comment]
@takayuki5168 
you need to merge vehicle info util first

**Comment by takayuki5168** [comment]
@taikitanaka3 I reopend after vehicle info was merged. So I think it's ready to merge

**Comment by taikitanaka3** [comment]
@TakaHoribe 
merge ready desu

**Comment by TakaHoribe** [comment]
@takayuki5168 @taikitanaka3 twist -> odomが直ってないです

**Comment by takayuki5168** [comment]
What do you think about this change for odometry? https://github.com/tier4/AutowareArchitectureProposal.iv/pull/481/commits/c0bca1571d84c92da4e65b64e862a74d1b9ae5c6

**Comment by takayuki5168** [comment]
@kenji-miyake Do you have any opinion about ↑?

**Comment by kenji-miyake** [comment]
I'm sorry I don't understand well... but looks good.

**Comment by takayuki5168** [comment]
Thanks, then this porting is done. If I don't forget anything...
- use autoware_auto_msgs
- remove COLCON_IGNORE
- use odometry

**Comment by taikitanaka3** [comment]
@TakaHoribe @mitsudome-r 
Topic name can be as default .iv `  <arg name="input/twist" default="/localization/twist" />`?

**Comment by TakaHoribe** [comment]
There is no longer input/twist. You can remove the twist from launch if possible.

**Comment by takayuki5168** [comment]
@TakaHoribe Then how do we get odometry by topic? Or we can ignore getting odometry by topic for now?

**Comment by takayuki5168** [comment]
Or do you mean we should change a topic name for odometry instead of twist?

**Comment by takayuki5168** [comment]
finished porting

**Comment by taikitanaka3** [comment]
- [] package depends  nav msgs would be missing
- [x]  build pass
- [x]  remove ignore

**Comment by takayuki5168** [comment]
@taikitanaka3 Thanks!! I totally forgot that.

**Review by taikitanaka3 — APPROVED** [review]
@mitsudome-r @TakaHoribe
merge ready desu

- [x] package depends nav msgs would be missing
- [x]  build pass
- [x] remove ignore
 
```
/localization/odmetry
```

**Review by TakaHoribe — APPROVED** [review]

**Pull request merged**
