### PR TITLE
modifying CMakeLists resolving CUDA, TensorRT dependencies pending

### PR DESCRIPTION
**Pull request by nik-tier4**
PR for porting traffic_light_classifier

CUDA dependencies are resolved. CMake is able to find CUDA.

cuDNN, TensorRT, OpenCV dependencies are still pending.

### CODE REVIEW

**Comment by nik-tier4** [comment]
cuda 11 installed successfully on ubuntu 20.4.  
Following:
```
sudo apt-get --purge remove "cublas" "cufft" "curand"  "cusolver" "cusparse" "npp" "nvjpeg" "cuda*" "nsight*"
sudo apt-get --purge remove "nvidia"
sudo reboot
wget https://developer.download.nvidia.com/compute/cuda/11.1.0/local_installers/cuda_11.1.0_455.23.05_linux.run
sudo sh cuda_11.1.0_455.23.05_linux.run
```
In options do not select the Nvidia drivers installations. Then Cuda 11 gets installed, need to add to PATH and LD_LIBRARY_PATH.

@mitsudome-r @dejanpan here is the PR

**Comment by mitsudome-r** [comment]
We have a replacement in https://github.com/tier4/Pilot.Auto/pull/70

**Comment by mitsudome-r** [comment]
I will reopen this pull request until we merge CUDA + TensorRT to ade.

**Comment by mitsudome-r** [comment]
@dejanpan
Here's the commands that I used to install CUDA and TensorRT.
```
#install tools
sudo apt update
sudo apt install software-properties-common


#install cuda
sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
sudo apt update

sudo apt install cuda-11-1

echo 'export PATH="/usr/local/cuda/bin:$PATH"' >> ~/.bashrc

#install TensorRT
sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/ /"

sudo apt update

sudo apt install libcudnn8-dev=8.0.4.30-1+cuda11.1 libcudnn8=8.0.4.30-1+cuda11.1 libnvinfer7=7.2.1-1+cuda11.1 \
libnvinfer-dev=7.2.1-1+cuda11.1 libnvinfer-plugin7=7.2.1-1+cuda11.1 libnvinfer-plugin-dev=7.2.1-1+cuda11.1 l\
ibnvonnxparsers7=7.2.1-1+cuda11.1 libnvonnxparsers-dev=7.2.1-1+cuda11.1 libnvparsers7=7.2.1-1+cuda11.1 \
libnvparsers-dev=7.2.1-1+cuda11.1
```

The commands uses repos from 1804 since there are not available as repos in 20.04 yet. (https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64/)

I decided to go with repos for Ubuntu18.04 as there is a report that we can use them with Ubuntu 20.04 as well. (http://home.hatanaka.info/article/475167174.html)
I've also confirmed that I can run `traffic_light_classifier` node that link against these libraries so I think it's alright for now.
We can replace them once NVIDIA releases them officially for Ubuntu 20.04.

**Comment by dejanpan** [comment]
@mitsudome-r @nik-tier4 I will re-state what I said today in the morning wrt https://github.com/tier4/Pilot.Auto/pull/53#issuecomment-720782530:

The problem is that `apt` does not allow to install the software on a separate file partition, e.g. `/opt/`. Hence we can not create a [docker volume](https://docs.docker.com/storage/volumes/)  which we could then chose to select in the [.aderc](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/.aderc-arm64-foxy) file or not.


If you see the `Dockerfile` below you will notice these 2 lines which allowed for exactly that:

```
sh cuda_8.0.61_375.26_linux-run --silent --toolkit --toolkitpath=/opt/cuda/ && \
sh cuda_8.0.61.2_linux-run --silent --accept-eula --installdir=/opt/cuda/ && \
```

What I will now do is, I will modify https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/tools/ade_image/apt-packages which will add these dependencies in the base [ade_image](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/.aderc-amd64-foxy#L6) and then if we do not want to merge this master, the worst that can happen is that we will have to define the base ade_image as `ade-foxy:master-cuda-tensorrt`.

```sh
FROM ubuntu:xenial as build_image

# CUDA apt dependencies - These will need to be present in ade_image too!!!
RUN apt-get update && \
    apt-get install -y \
         libatlas-base-dev \
         libgflags-dev \
         libgoogle-glog-dev \
         libhdf5-serial-dev \
         liblapack-dev \
         liblapack3 \
         libleveldb-dev \
         liblmdb-dev \
         libopenblas-base \
         libopenblas-dev \
         libopencv-dev \
         libprotobuf-dev \
         libsnappy-dev \
         protobuf-compiler \
        && rm -rf /var/lib/apt/lists/*

RUN cd /tmp && \
    curl -LO https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run && \
    curl -LO https://developer.nvidia.com/compute/cuda/8.0/Prod2/patches/2/cuda_8.0.61.2_linux-run && \
    sh cuda_8.0.61_375.26_linux-run --silent --toolkit --toolkitpath=/opt/cuda/ && \
    sh cuda_8.0.61.2_linux-run --silent --accept-eula --installdir=/opt/cuda/ && \
    rm -rf cuda*

COPY cudnn-8.0-linux-x64-v5.1.tgz /tmp/_cudnn.tar
RUN cd /tmp && \
    tar xf /tmp/_cudnn.tar && \
    cd cuda && \
    mv include/cudnn.h /opt/cuda/include/ && \
    mv lib64/libcudnn* /opt/cuda/lib64/ && \
    chmod a+r /opt/cuda/lib64/libcudnn* && \
    cd - && \
    rm -rf /tmp/_cudnn.tar /tmp/cuda

COPY env.sh /opt/cuda/.env.sh

FROM alpine
COPY --from=build_image /opt/cuda /opt/cuda
VOLUME /opt/cuda
CMD ["/bin/sh", "-c", "trap 'exit 147' TERM; tail -f /dev/null & wait ${!}"]
```

**Comment by dejanpan** [comment]
Upon second consideration I decided that I will give an alternative method a try (that would be able to install cuda, cudnn and tensorrt into `/opt/`):
1. cuda 11:
    1. wget https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda_11.1.1_455.32.00_linux.run
    1. sudo sh cuda_11.1.1_455.32.00_linux.run
1. https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux-tar
1. https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar


However the first step is failing with this error:

```
[INFO]: Initializing menu
[INFO]: Updating toolkitpath for: CUDA Toolkit 11.1
[INFO]: Updating toolkitpath for: CUDA Libraries 11.1
[INFO]: Updating toolkitpath for: CUDA Runtime 11.1
[INFO]: Updating toolkitpath for: cuda-cudart
[INFO]: Updating toolkitpath for: cuda-nvrtc
[INFO]: Updating toolkitpath for: libcublas11
[INFO]: Updating toolkitpath for: libcufft
[INFO]: Updating toolkitpath for: libcurand
[INFO]: Updating toolkitpath for: libcusolver
[INFO]: Updating toolkitpath for: libcusparse
[INFO]: Updating toolkitpath for: libnpp
[INFO]: Updating toolkitpath for: libnvjpeg
[INFO]: Updating toolkitpath for: CUDA Development 11.1
[INFO]: Updating toolkitpath for: cuda-cudart-dev
[INFO]: Updating toolkitpath for: cuda-driver-dev
[INFO]: Updating toolkitpath for: cuda-nvml-dev
[INFO]: Updating toolkitpath for: cuda-nvrtc-dev
[INFO]: Updating toolkitpath for: libcublas-dev
[INFO]: Updating toolkitpath for: libcufft-dev
[INFO]: Updating toolkitpath for: libcurand-dev
[INFO]: Updating toolkitpath for: libcusolver-dev
[INFO]: Updating toolkitpath for: libcusparse-dev
[INFO]: Updating toolkitpath for: libnpp-dev
[INFO]: Updating toolkitpath for: libnvjpeg-dev
[INFO]: Setup complete
[INFO]: Components to install: 
[INFO]: Driver
[INFO]: 455.32.00
[INFO]: Executing NVIDIA-Linux-x86_64-455.32.00.run --ui=none --no-questions --accept-license --disable-nouveau --no-cc-version-check --install-libglvnd  2>&1
[INFO]: Finished with code: 256
[ERROR]: Install of driver component failed.
[ERROR]: Install of 455.32.00 failed, quitting
```

**Comment by dejanpan** [comment]
@nik-tier4 where did you install this here: https://github.com/tier4/Pilot.Auto/pull/53#issuecomment-714208440, on your host or into https://github.com/tier4/AutowareArchitectureProposal/blob/ros2/.aderc?

**Comment by nik-tier4** [comment]
> @nik-tier4 where did you install this here: [#53 (comment)](https://github.com/tier4/Pilot.Auto/pull/53#issuecomment-714208440), on your host or into https://github.com/tier4/AutowareArchitectureProposal/blob/ros2/.aderc?

@dejanpan Just now noticed this message. I installed it to `.aderc`

**Pull request closed without merging**
