### PR TITLE
Use vehicle info utils

### PR DESCRIPTION
**Pull request by rej55**
## Description

Use vehicle_info_utils to get vehicle parameters.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [pull request guidelines][pull-request-guidelines]
- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by maxime-clem — APPROVED** [review]
Changes look good.
Do you want me to update the tests so that they do not fail ?

**Comment by rej55** [comment]
@maxime-clem 
Thanks! Is it possible to pass the test with vehicle_info_util? It would be helpful if you could.

**Comment by maxime-clem** [comment]
@rej55 I have added commit 5022f62 to reenable the tests.
The smoke tests are still failing but I think the smoke tests are broken (they expect a `-15` exit code but the nodes exit with `-2`).

Feel free to remove the commit if you prefer to do that change in a separated PR.

**Comment by rej55** [comment]
@maxime-clem
Thank you for the commit! I separated the parameter file for testing in https://github.com/tier4/AutowareArchitectureProposal.iv/pull/709/commits/54d7bf83dd108f97f2fc4cb9837c0479ebe86d28 .

**Pull request merged**
