### PR TITLE
update parameter descriptions of multi_object_tracker

### PR DESCRIPTION
**Pull request by taichiH**
## Description
update parameter descriptions of multi_object_tracker.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [pull request guidelines][pull-request-guidelines]
- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]

**Comment by h-ohta** [comment]
@yukkysaito @taichiH 
| Name                        | Type   | Description                                                                                                                                                                                                                                                                    |
| --------------------------- | ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| `max_area_matrix`           | double | Maximum area table for data association. If the area of the observed object's shape is larger than corresponding parameter, the association score is set to 0 to prevent erroneous association.                                                                                |
| `min_area_matrix`           | double | Minimum area table for data. If the area of the observed object's shape is smaller than corresponding parameter, the association score is set to 0 to prevent erroneous association.                                                                                           |

この2つって、次元はm^2ですか？例えばmaxを5、minを0.01とかにすれば、0.01m^2〜5m^2の面積のオブジェクトがトラッキングに使われるということでしょうか？

**Comment by yukkysaito** [comment]
>この2つって、次元はm^2ですか？例えばmaxを5、minを0.01とかにすれば、0.01m^2〜5m^2の面積のオブジェクトがトラッキングに使われるということでしょうか？

yesです :pray:

**Comment by h-ohta** [comment]
@yukkysaito ありがとうございます
@taichiH 単位と例をREADMEに載せておくと親切だなと思うのですがいかがでしょうか？

**Comment by h-ohta** [comment]
一旦draftに戻しておきます

**Pull request closed without merging**
