### PR TITLE
port planning error monitor package

### PR DESCRIPTION
**Pull request by purewater0901**
## Description
planning error monitorのポート

変更内容
autoware_planning_msgs → autoware_auto_planning_msgs

TODO:
autoware_utilsがautoのmsgsに対応したら再度ビルドして、問題なくビルドが通ることを確認する。

## Review Procedure
ビルドができること

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [pull request guidelines][pull-request-guidelines]
- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by taikitanaka3** [comment]
@purewater0901 
follow recent commit and change description here too .auto message please
```
| `~/input/trajectory` | `autoware_planning_msgs/Trajectory` | Planned Trajectory by planning modules |
```

**Comment by purewater0901** [comment]
@taikitanaka3 I just merged the latest change in use-auto-msgs branch and also changed the description that you mentioned

**Review by taikitanaka3 — APPROVED** [review]
LGTM

- [x] package depend
- [x] remove ignore
- [x] build pass
- [x] launch success
```
ros2 launch planning_error_monitor planning_error_monitor.launch.xml 
[INFO] [launch]: All log files can be found below /home/t4tanaka/.ros/log/2021-11-08-09-50-21-381757-t4tanaka-DAIV-DGZ530-38498
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [planning_error_monitor-1]: process started with pid [38508]
```

**Comment by taikitanaka3** [comment]
@TakaHoribe 
merge ready as porting!

**Comment by tkimura4** [comment]
Could you update packages.xml?
This package depends `autoware_auto_planning_msgs`.

**Comment by purewater0901** [comment]
@tkimura4 I think I already put that dependency into the package.xml file. [Here](https://github.com/tier4/AutowareArchitectureProposal.iv/blob/auto/planning_error_monitor/planning/planning_diagnostics/planning_error_monitor/package.xml#L13) is the code.

**Review by TakaHoribe — APPROVED** [review]

**Pull request merged**
