### PR TITLE
auto/fix_inline_expansion

### PR DESCRIPTION
**Pull request by taikitanaka3**
## Description

tf2_eigen.hが定義されていなかったため arc_lane_util.hppにinlineで定義されている関数がruntime時に死ぬため修正
 

## Review Procedure

柏の葉の地図で死なないことの確認
image

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [pull request guidelines][pull-request-guidelines]
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by taikitanaka3** [comment]
[Q] @kenji-miyake @wep21 
.hppにあるとruntime時におちるのですが、こちらなにかわかりそうでしょうか？（.ivの方ではでは正常に動いてました。）

**Comment by kenji-miyake** [comment]
mm... I'm sorry I'm not sure. :pleading_face:

**Comment by TakaHoribe** [comment]
こういう問題の適切な追い方が知りたいぴえん

**Comment by kmiya** [comment]
I'm not sure, but there might be a missing header like this <https://github.com/tier4/AutowareArchitectureProposal.iv/pull/664>.

**Comment by taikitanaka3** [comment]
@kmiya 
thankyou  #include <tf2_geometry_msgs/tf2_geometry_msgs.h> is already in this file and

**Comment by taikitanaka3** [comment]
there may be some linking error in Eigen
https://github.com/ros2/geometry2/pull/368

**Comment by taikitanaka3** [comment]
tf2_geometry_msgs was not the package which is used here, instead thsi package was necessary 
http://docs.ros.org/en/jade/api/tf2_eigen/html/tf2__eigen_8h.html

but tf2_geometry_msgs has a template and it doesnt print error when building

**Review by tkimura4 — APPROVED** [review]
LGTM

image

**Pull request merged**
