### PR TITLE
Ros2 v0.8.0 autoware state monitor

### PR DESCRIPTION
**Pull request by wep21**
Depends on https://github.com/tier4/AutowareArchitectureProposal.iv/pull/274
### TODO
- [ ]  check usage of service server

### CODE REVIEW

**Comment by k0suke-murakami** [comment]
- [ ]  Build passed

- [ ] ros2 run success
Node: 

- [x] Test  passed

**Comment by k0suke-murakami** [comment]
Build error happened. 
It seems like need to port with/after `autoware_system_msgs` 

```
In file included from /home/kosuke/autoware_0_8/src/autoware/pilot.auto/system/autoware_state_monitor/include/autoware_state_monitor/autoware_state_monitor_node.hpp:18,
                 from /home/kosuke/autoware_0_8/src/autoware/pilot.auto/system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp:15:
/home/kosuke/autoware_0_8/src/autoware/pilot.auto/system/autoware_state_monitor/include/autoware_state_monitor/autoware_state.hpp: In function ‘AutowareState fromString(const string&)’:
/home/kosuke/autoware_0_8/src/autoware/pilot.auto/system/autoware_state_monitor/include/autoware_state_monitor/autoware_state.hpp:45:30: error: ‘FINALIZING’ is not a member of ‘StateMessage’ {aka ‘autoware_system_msgs::msg::AutowareState_<std::allocator<void> >’}
   45 |   if (state == StateMessage::FINALIZING) {return AutowareState::Finalizing;}

```

**Comment by wep21** [comment]
@k0suke-murakami Yes, as I commented, this pr depends on https://github.com/tier4/AutowareArchitectureProposal.iv/pull/274, so I guess it's better to review and merge https://github.com/tier4/AutowareArchitectureProposal.iv/pull/274 in advance.

**Comment by k0suke-murakami** [comment]
https://github.com/tier4/AutowareArchitectureProposal.iv/pull/281#issuecomment-772953988
It seems the same action needs to be taken. Could you work on this? @wep21

**Comment by k0suke-murakami** [comment]
- [x]  Build passed

- [x] ros2 run success
Node: autoware_state_monitor 

- [x] Test  passed

**Comment by k0suke-murakami** [comment]
- [x]  Build passed
Package: autoware_state_monitor

- [x] ros2 run success
Node: autoware_state_monitor 

- [x] Test  passed

**Pull request merged**
