### PR TITLE
Port velocity debug tools

### PR DESCRIPTION
**Pull request by TakaHoribe**
Note: based on 0.8.0

```
$ python3 ./src/autoware/pilot.auto/planning/scenario_planning/common/motion_velocity_optimizer/scripts/closest_velocity_checker.py
```

```
$ python3 ./src/autoware/pilot.auto/planning/scenario_planning/common/motion_velocity_optimizer/scripts/trajectory_visualizer.py
```

### CODE REVIEW

**Comment by wep21** [comment]
@TakaHoribe 
How about adding install() in CMakeLists.txt as below to execute script with `ros2 run`?
`install(PROGRAMS
          scripts/trajectory_visualizer.py
          scripts/closest_velocity_checker.py
        DESTINATION lib/${PROJECT_NAME})`

**Comment by wep21** [comment]
The debug tools seem to work correctly.
Screenshot from 2021-01-14 17-55-19
Screenshot from 2021-01-14 17-56-29

**Comment by TakaHoribe** [comment]
@wep21 
 - Add install for scripts in Cmakelists.txt
 - change `python` to `python3` in scripts

**Review by wep21 — APPROVED** [review]
LGTM

**Pull request merged**
