### PR TITLE
use autoware_auto_msgs in autoware_utils

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

autoware_utilsの.auto porting

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [pull request guidelines][pull-request-guidelines]
- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[clang-tidy-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/ClangTidyGuideline/
[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[pull-request-guidelines]: https://tier4.github.io/autoware.proj/tree/main/developer_guide/PullRequestGuideline/
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by takayuki5168** [comment]
@kenji-miyake @TakaHoribe autoware_utilsのautoware_planning_msgs -> autoware_auto_planning_msgsの置き換えです
いろんなパッケージに依存しているのでこちらも早めのマージがよいかもです

**Comment by kenji-miyake** [comment]
@takayuki5168 Could you investigate the reason for CI failure?

**Comment by takayuki5168** [comment]
It's because this one has not been merged yet. https://github.com/tier4/autoware_auto_msgs/pull/4
I'll close and open this PR.

**Comment by takayuki5168** [comment]
@kenji-miyake Ahh but many packages which use iv_msgs depends on autoware_utils which now uses auto_msgs, so there are building errors. How do you think should this PR be merged?

**Comment by takayuki5168** [comment]
And once this PR is merged, there will be always building errors in all other PRs ...

**Comment by kenji-miyake** [comment]
@takayuki5168 As a test, could you send a PR that specifies this PR as the base branch?

**Comment by takayuki5168** [comment]
@kenji-miyake Did it. https://github.com/tier4/AutowareArchitectureProposal.iv/pull/481

**Review by taikitanaka3 — APPROVED** [review]
```

```
100% tests passed, 0 tests failed out of 5

Label Time Summary:
copyright     =   2.37 sec*proc (1 test)
cppcheck      =   0.34 sec*proc (1 test)
gtest         =   5.10 sec*proc (1 test)
lint_cmake    =   0.27 sec*proc (1 test)
linter        =   3.25 sec*proc (4 tests)
xmllint       =   0.27 sec*proc (1 test)

Total Test time (real) =   8.35 sec
Finished <<< autoware_utils [8.47s]

Summary: 1 package finished [9.19s]
```
```

LGTM

**Comment by taikitanaka3** [comment]
@takayuki5168 @rej55 
these commits  are depend on this so rebase please.
https://github.com/tier4/AutowareArchitectureProposal.iv/pull/495/files
 #481
 #498

**Comment by takayuki5168** [comment]
@taikitanaka3 Ohh wait... I haven't removed COLCON_IGNORE yet...

**Pull request merged**
